language: node_js
node_js: "6"


before_install:
  - git config --global user.name "hellowor1d"
  - git config --global user.email "1034597776@qq.com"
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install

# Travis-CI Caching
cache:
  directories:
    - node_modules

#before_script:
  - npm install -g hexo-cli

script:
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Update Blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/hellowor1d/hellowor1d.github.io.git
