language: node_js
node_js: "6"


branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/hellowor1d/hellowor1d.github.io.git


cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install -g hexo-cli
  - npm install hexo-deployer-git
  - npm install

#before_script:
#  - npm install -g hexo-cli

script:
  - hexo generate
  - hexo deploy
# after_script:
#   - cd public
#   - git init
#   - git config user.name "hellowor1d"
#   - git config user.email "1034597776@qq.com"
#   - git add .
#   - git commit -m "Update blog"
#   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
